#!/bin/bash
# Setting up HDFS and MapReduce at startup!


# if /data/hadoop exists --> no namenode format needed
if [ ! -d "/data/hadoop" ]; then
	echo "No HDFS folder in data folder. Format Namenode..."
	mkdir /data/hadoop
	chmod 1777 /data/hadoop
  sudo -u hdfs hdfs namenode -format
else
	echo "Found HDFS folder in data folder. Reuse /data/hadoop."
fi


# start the HDFS Service generate all necessary directories
for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do sudo service $x start ; done
sudo /usr/bin/init-hdfs.sh


# delete cache directory in HDFS
su -s /bin/bash hdfs -c '/usr/bin/hadoop fs -rmr /var/lib/hadoop-hdfs/cache/mapred/mapred/staging'

# add home dir for root
sudo -u hdfs hadoop fs -mkdir -p /user/root
sudo -u hdfs hadoop fs -chown root /user/root

# http://blog.cloudera.com/blog/2013/11/migrating-to-mapreduce-2-on-yarn-for-operators/
#sudo /usr/bin/adapt-mapred-config.sh

sudo service hadoop-yarn-resourcemanager start
sudo service hadoop-yarn-nodemanager start
sudo service hadoop-mapreduce-historyserver start

export HADOOP_MAPRED_HOME=/usr/lib/hadoop-mapreduce


#print ip
hostname=$(grep "$HOSTNAME" /etc/hosts|awk '{print $1}')
echo "Congratulations! Cluster is running on $hostname"

# end with command line if BASH command is set
if [ ${EXEC_BASH} == "true" ]
then
	/bin/bash
fi

